@startuml
left to right direction
skinparam shadowing false
skinparam packageStyle rectangle
skinparam actorStyle stickman

skinparam ArrowColor #334155
skinparam ActorBorderColor #1d4ed8
skinparam ActorBackgroundColor #ffffff
skinparam ActorFontColor #0f172a
skinparam ActorFontStyle bold

skinparam UsecaseBorderColor #0f172a
skinparam UsecaseBackgroundColor #f8fafc
skinparam UsecaseFontColor #0f172a
skinparam UsecaseFontStyle bold

skinparam RectangleBorderColor #475569
skinparam RectangleBackgroundColor #ffffff

actor "Employee" as Employee
actor "HR Manager" as HRManager
actor "System Administrator" as SystemAdministrator

rectangle "Compliance & Audit - Corporate Governance" {
    usecase "UC60: Report Policy Violations" as UC_Main
    usecase "Fill Anonymous Complaint Form" as UC_FillAnon
    usecase "Strip Metadata & Encrypt File" as UC_StripExif
    usecase "Review Grievance Ticket" as UC_ReviewTicket

    Employee -- UC_Main
    HRManager -- UC_ReviewTicket
    SystemAdministrator -- UC_StripExif
    UC_Main .> UC_FillAnon : <<include>>
    UC_Main .> UC_StripExif : <<include>>
    UC_Main .> UC_ReviewTicket : <<include>>
}
@enduml
