@startuml
title Platform Services Use Case Diagram

left to right direction
skinparam shadowing false
skinparam packageStyle rectangle
skinparam actorStyle stickman

skinparam ActorBorderColor #0f172a
skinparam ActorBackgroundColor #ffffff
skinparam ActorFontColor #0f172a
skinparam ActorFontStyle bold

skinparam RectangleBorderColor #0f172a
skinparam RectangleBackgroundColor #ffffff
skinparam RectangleFontColor #0f172a
skinparam RectangleFontStyle bold

skinparam ArrowColor #0f172a
skinparam ArrowThickness 1.2

skinparam usecase {
    BackgroundColor #f1f5f9
    BorderColor #0f172a
    FontColor #0f172a
    FontStyle normal
}


actor "System Administrator" as SysAdmin

rectangle "Platform Services" {
    usecase "Manage System Integration" as UC_Int
    usecase "Manage API Gateway" as UC_API
    usecase "Manage User Authentication" as UC_Auth
    usecase "Manage Role Permissions" as UC_Role
    usecase "Manage Mobile Portal" as UC_Mob
    usecase "Manage Notifications Engine" as UC_Notif
}

actor "Employee" as Emp
actor "HR Manager" as HR

UC_Int ..> UC_API : <<include>>
UC_Auth ..> UC_Role : <<include>>
UC_Notif ..> UC_Mob : <<extend>>

SysAdmin -- UC_Int
SysAdmin -- UC_API
SysAdmin -- UC_Auth
SysAdmin -- UC_Role

UC_Auth -- Emp
UC_Mob -- Emp
UC_Notif -- Emp

UC_Role -- HR
UC_Notif -- HR
@enduml
