@startuml
left to right direction
skinparam shadowing false
skinparam packageStyle rectangle
skinparam actorStyle stickman

skinparam ArrowColor #334155
skinparam ActorBorderColor #1d4ed8
skinparam ActorBackgroundColor #ffffff
skinparam UsecaseBorderColor #0f172a
skinparam UsecaseBackgroundColor #f8fafc
skinparam RectangleBorderColor #475569
skinparam RectangleBackgroundColor #ffffff

actor "Employee" as Employee
actor "Payroll Administrator" as PayrollAdministrator

rectangle "Payroll & Compensation - Payroll Engine" {
    usecase "UC28: Process Payslip Discrepancy" as UC_Main
    usecase "Raise Salary Claim Ticket" as UC_RaiseTicket
    usecase "Audit Discrepancy Logic" as UC_AuditClaim
    usecase "Create Retroactive Adjustment" as UC_AdjustPayroll

    Employee -- UC_Main
    UC_Main .> UC_RaiseTicket : <<include>>
    UC_Main .> UC_AuditClaim : <<include>>
    UC_Main .> UC_AdjustPayroll : <<include>>
    UC_AuditClaim -- PayrollAdministrator
}
@enduml
