@startuml
left to right direction
skinparam shadowing false
skinparam packageStyle rectangle
skinparam actorStyle stickman

skinparam ArrowColor #334155
skinparam ActorBorderColor #1d4ed8
skinparam ActorBackgroundColor #ffffff
skinparam ActorFontColor #0f172a
skinparam ActorFontStyle bold

skinparam UsecaseBorderColor #0f172a
skinparam UsecaseBackgroundColor #f8fafc
skinparam UsecaseFontColor #0f172a
skinparam UsecaseFontStyle bold

skinparam RectangleBorderColor #475569
skinparam RectangleBackgroundColor #ffffff

actor "System Administrator" as SystemAdministrator
actor "Employee" as Employee

rectangle "Platform & Security (Web) - Authentication & IAM" {
    usecase "UC49: Authenticate User & SSO" as UC_Main
    usecase "Verify IdP Assertion Token" as UC_VerifyToken
    usecase "Validate MFA Code" as UC_MFA
    usecase "Issue JWT Session Token" as UC_IssueJWT

    SystemAdministrator -- UC_Main
    Employee -- UC_Main
    UC_Main .> UC_VerifyToken : <<include>>
    UC_Main .> UC_MFA : <<include>>
    UC_Main .> UC_IssueJWT : <<include>>
}
@enduml
