@startuml
left to right direction
skinparam shadowing false
skinparam packageStyle rectangle
skinparam actorStyle stickman

skinparam ArrowColor #334155
skinparam ActorBorderColor #1d4ed8
skinparam ActorBackgroundColor #ffffff
skinparam UsecaseBorderColor #0f172a
skinparam UsecaseBackgroundColor #f8fafc
skinparam RectangleBorderColor #475569
skinparam RectangleBackgroundColor #ffffff

actor "All Users" as AllUsers
actor "Identity Provider (Azure AD/Google)" as IdentityProviderAzureADGoogle
actor "Security Engine" as SecurityEngine

rectangle "Platform & Security (Web) - Authentication & IAM" {
    usecase "UC49: Authenticate User & SSO" as UC_Main
    usecase "Verify IdP Assertion Token" as UC_VerifyToken
    usecase "Validate MFA Code" as UC_MFA
    usecase "Issue JWT Session Token" as UC_IssueJWT

    AllUsers -- UC_Main
    UC_Main .> UC_VerifyToken : <<include>>
    UC_Main .> UC_MFA : <<include>>
    UC_Main .> UC_IssueJWT : <<include>>
    UC_VerifyToken -- IdentityProviderAzureADGoogle
    UC_IssueJWT -- SecurityEngine
}
@enduml
