@startuml
left to right direction
skinparam shadowing false
skinparam packageStyle rectangle
skinparam actorStyle stickman

skinparam ArrowColor #334155
skinparam ActorBorderColor #1d4ed8
skinparam ActorBackgroundColor #ffffff
skinparam ActorFontColor #0f172a
skinparam ActorFontStyle bold

skinparam UsecaseBorderColor #0f172a
skinparam UsecaseBackgroundColor #f8fafc
skinparam UsecaseFontColor #0f172a
skinparam UsecaseFontStyle bold

skinparam RectangleBorderColor #475569
skinparam RectangleBackgroundColor #ffffff

actor "System Administrator" as SystemAdministrator
actor "HR Manager" as HRManager

rectangle "Platform & Security (Web) - Integration API" {
    usecase "UC51: Manage API Keys & Webhooks" as UC_Main
    usecase "Generate API Secret Token" as UC_GenSecret
    usecase "Validate Webhook Endpoint" as UC_ValWebhook
    usecase "Log Security Audit Event" as UC_AuditLog

    SystemAdministrator -- UC_Main
    HRManager -- UC_AuditLog
    UC_Main .> UC_GenSecret : <<include>>
    UC_Main .> UC_ValWebhook : <<include>>
    UC_Main .> UC_AuditLog : <<include>>
}
@enduml
