@startuml
left to right direction
skinparam shadowing false
skinparam packageStyle rectangle
skinparam actorStyle stickman

skinparam ArrowColor #334155
skinparam ActorBorderColor #1d4ed8
skinparam ActorBackgroundColor #ffffff
skinparam UsecaseBorderColor #0f172a
skinparam UsecaseBackgroundColor #f8fafc
skinparam RectangleBorderColor #475569
skinparam RectangleBackgroundColor #ffffff

actor "HR Manager" as HRManager
actor "Email/SMS Gateway" as EmailSMSGateway
actor "Employee" as Employee

rectangle "Platform & Security (Web) - Notifications Engine" {
    usecase "UC52: Configure Email & SMS Templates" as UC_Main
    usecase "Render Dynamic Template" as UC_RenderTemp
    usecase "Filter Recipient Scope" as UC_FilterScope
    usecase "Dispatch Email/SMS Message" as UC_DispatchMail

    HRManager -- UC_Main
    UC_Main .> UC_RenderTemp : <<include>>
    UC_Main .> UC_FilterScope : <<include>>
    UC_Main .> UC_DispatchMail : <<include>>
    UC_DispatchMail -- EmailSMSGateway
    UC_DispatchMail -- Employee
}
@enduml
