@startuml
left to right direction
skinparam shadowing false
skinparam packageStyle rectangle
skinparam actorStyle stickman

skinparam ArrowColor #334155
skinparam ActorBorderColor #1d4ed8
skinparam ActorBackgroundColor #ffffff
skinparam ActorFontColor #0f172a
skinparam ActorFontStyle bold

skinparam UsecaseBorderColor #0f172a
skinparam UsecaseBackgroundColor #f8fafc
skinparam UsecaseFontColor #0f172a
skinparam UsecaseFontStyle bold

skinparam RectangleBorderColor #475569
skinparam RectangleBackgroundColor #ffffff

actor "Employee" as Employee
actor "Department Manager" as DepartmentManager
actor "Payroll Administrator" as PayrollAdministrator

rectangle "Time & Attendance Management - Attendance Engine" {
    usecase "UC11: Record Attendance" as UC_Main
    usecase "Capture Punch Timestamp" as UC_Punch
    usecase "Validate Shift Schedule" as UC_CheckShift
    usecase "Log Late/Early Status" as UC_LogLate

    Employee -- UC_Main
    DepartmentManager -- UC_LogLate
    PayrollAdministrator -- UC_LogLate
    UC_Main .> UC_Punch : <<include>>
    UC_Main .> UC_CheckShift : <<include>>
    UC_Main .> UC_LogLate : <<include>>
}
@enduml
