@startuml
left to right direction
skinparam shadowing false
skinparam packageStyle rectangle
skinparam actorStyle stickman

skinparam ArrowColor #334155
skinparam ActorBorderColor #1d4ed8
skinparam ActorBackgroundColor #ffffff
skinparam ActorFontColor #0f172a
skinparam ActorFontStyle bold

skinparam UsecaseBorderColor #0f172a
skinparam UsecaseBackgroundColor #f8fafc
skinparam UsecaseFontColor #0f172a
skinparam UsecaseFontStyle bold

skinparam RectangleBorderColor #475569
skinparam RectangleBackgroundColor #ffffff

actor "Department Manager" as DepartmentManager
actor "Employee" as Employee
actor "HR Manager" as HRManager

rectangle "Time & Attendance Management - Shift Rostering" {
    usecase "UC15: Create Shift Schedules" as UC_Main
    usecase "Define Shift Master Templates" as UC_DefTemplates
    usecase "Assign Roster Grid" as UC_GridAssign
    usecase "Validate Rest Hours Rule" as UC_CheckRest

    DepartmentManager -- UC_Main
    HRManager -- UC_Main
    Employee -- UC_GridAssign
    UC_Main .> UC_DefTemplates : <<include>>
    UC_Main .> UC_GridAssign : <<include>>
    UC_Main .> UC_CheckRest : <<include>>
}
@enduml
