@startuml
left to right direction
skinparam shadowing false
skinparam packageStyle rectangle
skinparam actorStyle stickman

skinparam ArrowColor #334155
skinparam ActorBorderColor #1d4ed8
skinparam ActorBackgroundColor #ffffff
skinparam UsecaseBorderColor #0f172a
skinparam UsecaseBackgroundColor #f8fafc
skinparam RectangleBorderColor #475569
skinparam RectangleBackgroundColor #ffffff

actor "HR Manager" as HRManager
actor "System Administrator" as SystemAdministrator

rectangle "Time & Attendance Management - Absence & Leave" {
    usecase "UC19: Configure Holidays & Calendar" as UC_Main
    usecase "Define Yearly Working Days" as UC_InitYear
    usecase "Add Public Holiday List" as UC_AddHolidays
    usecase "Set Compensatory Workdays" as UC_SetComp

    HRManager -- UC_Main
    SystemAdministrator -- UC_Main
    UC_Main .> UC_InitYear : <<include>>
    UC_Main .> UC_AddHolidays : <<include>>
    UC_Main .> UC_SetComp : <<include>>
}
@enduml
